### ISSUE TITLE
[1.16.5] Yttr causes game crash when loading in

### ISSUE THREAD

**Issue by AlexisBloodwood** [unascribed/Yttr#2]
Yea so, when I try to load in it throws a main/FATAL unreported exception error which I have uploaded below. Unfortunately I cannot upload the entire log as another mod is trying to load every recipe from it despite me not having the dependents for it.

https://0bin.net/paste/RVtQ+49x#mtMJBY1LTuS7gw94NKaaVW8iZBOnPZSaqd41qdID4Vj

**Comment by exaskye** [comment]
Mixin conflict with another mod; kind of hard to tell what's conflicting though..

It's in the HUD renderer, where I handle fixing suffocation rendering for the Effector. Does that bring any mods to mind?

**Comment by AlexisBloodwood** [comment]
On the HUD? I do have KronHUD, Hwyla, BetterF3, Can I mine this block?, Erroring Entity Remover, Replay mod and Xaero's Minimap and World map

**Comment by exaskye** [comment]
`optifabric: OptiFabric 1.9.6`

OptiFine does all sorts of unspeakable things to the rendering system. Does this happen without it installed?

**Comment by AlexisBloodwood** [comment]
🥲 aaand its Optifine, time to cry in a corner

**Comment by exaskye** [comment]
Not really anything I can do about an OptiFine conflict, unfortunately.

Sodium and Lithium I can check the source and make compatibility stuff for, and I will, but with OptiFine I'm just kinda screwed.
